name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    
      - name: Slack Notification Start
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_ICON_EMOJI: ":ssm:"
          SLACK_TITLE: ":android: 빌드 시작 / 버전 : $($) / 브랜5치 : $"
          SLACK_USERNAME: "ssm-mobile-builder-bot"
          SLACK_CHANNEL: "#notification-android"
          SLACK_COLOR: "#CCCCCC"
          SLACK_MESSAGE: "commit : 41424"  
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
          
      - name: Decode Keystore
        run: echo ${{ secrets.KEY_STORE_BASE64 }} | base64 -d > keystore.jks
          echo keystore.jks
        
      - name: Decode Keystore2
        run: echo $KEY_STORE_BASE64 | base64 -d > keystore2.jks
          echo keystore2.jks
  
#       - name: Grant execute permission for gradlew
#         run: chmod +x gradlew
#       - name: Build with Gradle
#         run: ./gradlew app:bundleRelease
#         env:
#           KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
#           KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
#           KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          
#       - name: Slack Notification Finish With Success
#         uses: rtCamp/action-slack-notify@v2
#         if: success()
#         env:
#           SLACK_ICON_EMOJI: ":android:"
#           SLACK_TITLE: ":android2: 빌드 성공 / 버전 : $($) / 브랜치 : $"
#           SLACK_USERNAME: "ssm-mobile-builder-bot"
#           SLACK_CHANNEL: "#notification-android"
#           SLACK_COLOR: "#00BFA5"
#           SLACK_MESSAGE: "commit : $\n<$/$/$|파일다운로드>, <$$/|브라우징>"
#           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

#       - name: Slack Notification Finish With Fail
#         uses: rtCamp/action-slack-notify@v2
#         if: failure()
#         env:
#           SLACK_ICON_EMOJI: ":android:"
#           SLACK_TITLE: ":android2: 빌드 실패 / 버전 : $($) / 브랜치 : $"
#           SLACK_USERNAME: "ssm-mobile-builder-bot"
#           SLACK_CHANNEL: "#notification-android"
#           SLACK_COLOR: "#FF5252"
#           SLACK_MESSAGE: "commit : $"
#           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
